# -*- coding: utf-8 -*-
"""Eclat and FP growth

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TG3h-Hu4Veh6wG8BCiRGdaxgdOC23wwJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Market_Basket_Optimisation.csv",header=None)

df.head()

df.tail()

df.describe()

df.shape

!pip install pyECLAT

import pandas as pd
from pyECLAT import ECLAT

eclat = ECLAT(data=df)

indices, support = eclat.fit(
    min_support=0.03,
    min_combination=2,
    max_combination=2
)

result = pd.DataFrame(
    support.items(),
    columns=['Itemset', 'Support']
)

print(result.sort_values(by='Support', ascending=False))

from pyECLAT import ECLAT
import pandas as pd

eclat = ECLAT(df)

indices, support = eclat.fit(min_support=0.03,
                       min_combination=2,
                       max_combination=2)

for itemset, sup_ab in support.items():

    A, B = itemset.split('&')

    sup_a = (df == A.strip()).any(axis=1).mean()
    sup_b = (df == B.strip()).any(axis=1).mean()

    confidence = sup_ab / sup_a
    lift = confidence / sup_b

    print("Itemset:", itemset)
    print("Support:", round(sup_ab, 4))
    print("Confidence:", round(confidence, 4))
    print("Lift:", round(lift, 4))
    print("-" * 30)

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

# Load dataset
df = pd.read_csv('/content/Market_Basket_Optimisation.csv', header=None)

# Convert dataframe into transaction list
transactions = []

for i in range(len(df)):
    transactions.append(
        [str(item) for item in df.iloc[i].dropna().values]
    )

# Transaction Encoding
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_array, columns=te.columns_)

# Apply FP-Growth
frequent_itemsets = fpgrowth(
    df_encoded,
    min_support=0.03,
    use_colnames=True
)

print("Frequent Itemsets:")
print(frequent_itemsets)

# Generate Association Rules
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.2
)

# Display required columns
result = rules[['antecedents',
                'consequents',
                'support',
                'confidence',
                'lift']]

print("\nAssociation Rules:")
print(result)